# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-21 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
    ]
